title: Your awesome title
email: your-email@example.com
description: >-
  My site by Caleb Miller
baseurl: "/sample-project-site"
url: ""
github_username: calebmiller010
repository: "calebmiller010/sample-project-site"

# Build settings
theme: jekyll-theme-cayman

disqus:
  shortname: disqus_r8Y42vnBgW